name: Flutter iOS Build and Deploy

on:
  push:
    branches:
      - main  # 触发工作流的分支名，根据你的需求修改

jobs:
  build:
    runs-on: macos-latest  # GitHub 提供的 macOS 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'  # 替换为你的 Flutter 版本

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS
      run: |
        flutter build ios --no-codesign

    - name: Archive iOS App
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner archive -archivePath ${{ github.workspace }}/Runner.xcarchive

    - name: Upload iOS Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: ${{ github.workspace }}/Runner.xcarchive
