name: Build iOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          cd ios
          flutter build ios --no-codesign
        env:
          FLUTTER_BUILD_MODE: release

      - name: Archive iOS
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration AppStoreDistribution archive -archivePath ${{ github.workspace }}/Runner.xcarchive
        env:
          FLUTTER_BUILD_MODE: release
